---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: k3s-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.1.100-192.168.1.119
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: k3s-advertisement
  namespace: metallb-system