apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  namespace: external-dns
spec:
  template:
    spec:
      containers:
      - name: external-dns
        envFrom:
        - secretRef:
            name: pihole-password
        args:
          - --source=service
          - --source=gateway
          - --source=gateway-httproute
          - --registry=noop
          - --policy=upsert-only
          - --provider=pihole
          - --pihole-api-version=6
          - --pihole-server=http://pihole-web.pihole.svc.cluster.local
