apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: envoy-gateway-system

helmCharts:
  - name: envoy-gateway
    releaseName: gateway-helm
    namespace: envoy-gateway-system
    repo: https://github.com/vabalops/home-server/tree/main/cluster/core/envoy-gateway/gateway-helm
    version: 1.6.3
    valuesFile: values.yaml
    includeCRDs: true
