apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: envoy-gateway-system

helmCharts:
  - name: envoy-gateway
    releaseName: envoy-gateway
    namespace: envoy-gateway-system
    repo: oci://docker.io/envoyproxy/gateway-helm
    version: 1.6.3
    valuesFile: values.yaml
    includeCRDs: true
