apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: envoy
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
