apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: armandasdev@gmail.com
    privateKeySecretRef:
      name: letsencrypt-private-key-staging
    solvers:
    - http01:
        gatewayHTTPRoute: {}

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: armandasdev@gmail.com
    privateKeySecretRef:
      name: letsencrypt-private-key-production
    solvers:
    - http01:
        gatewayHTTPRoute: {}